# Ansible Inventory — go-web-app K8s Cluster
# IPs come from: terraform output (on Jenkins VM)
# Update IPs after every terraform apply (new EC2 = new IPs)

[k8s_master]
18.206.136.124 ansible_user=ubuntu ansible_ssh_private_key_file=~/terraform-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s_worker]
44.192.6.170 ansible_user=ubuntu ansible_ssh_private_key_file=~/terraform-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s_all:children]
k8s_master
k8s_worker
