# Ansible Inventory — go-web-app K8s Cluster
# IPs come from: terraform output (on Jenkins VM)
# ⚠️  Update IPs after every terraform apply — new EC2 = new public IP

[k8s_master]
master ansible_host=18.206.136.124

[k8s_worker]
worker ansible_host=44.192.6.170

[k8s_all:children]
k8s_master
k8s_worker

[k8s_all:vars]
ansible_user                 = ubuntu
ansible_ssh_private_key_file = ~/terraform-key.pem
